export const technologies = [
  {
    image: "/TechImage/Typescript.svg",
    alt: "Typescript",
    width: 70,
    height: 64,
    imageName: "Typescript",
  },
  {
    image: "/TechImage/React.png",
    alt: "React",
    width: 70,
    height: 64,
    imageName: "React",
  },
  {
    image: "/TechImage/React-Native.png",
    alt: "React Native",
    width: 83,
    height: 72,
    imageName: "React Native",
  },
  {
    image: "/TechImage/Redux.png",
    alt: "Redux",
    width: 78,
    height: 75,
    imageName: "Redux",
  },
  {
    image: "/TechImage/Express.png",
    alt: "Express",
    width: 78,
    height: 43,
    imageName: "ExpressJS",
  },
  {
    image: "/TechImage/Next.png",
    alt: "Next",
    width: 78,
    height: 78,
    imageName: "NextJS",
  },
  {
    image: "/TechImage/nodejs.png",
    alt: "NodeJS",
    width: 70,
    height: 78,
    imageName: "NodeJS",
  },
  {
    image: "/TechImage/Prisma.svg",
    alt: "Prisma ORM",
    width: 70,
    height: 78,
    imageName: "Prisma ORM",
  },
  {
    image: "/TechImage/sql.png",
    alt: "PostgreSQL",
    width: 76,
    height: 79,
    imageName: "PostgreSQL",
  },
  {
    image: "/TechImage/git.png",
    alt: "Git",
    width: 78,
    height: 79,
    imageName: "Git",
  },
  {
    image: "/TechImage/html.png",
    alt: "HTML",
    width: 68,
    height: 0,
    imageName: "HTML",
  },
  {
    image: "/TechImage/css.png",
    alt: "CSS",
    width: 69,
    height: 0,
    imageName: "CSS",
  },
  {
    image: "/TechImage/tailwind.png",
    alt: "Tailwind",
    width: 79,
    height: 79,
    imageName: "Tailwind",
  },
];
