import Navbar from "@/components/navbar/page";
import "./globals.css";
import { Inter, Prompt } from "next/font/google";
import Providers from "./providers";

const prompt = Prompt({
  weight: ["300", "500", "700"],
  styles: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html id="home" lang="en" className="!scroll-smooth" data-theme="dark">
      <body className={prompt.className}>
       <Providers>
        <div className="background"></div>
        <div className="background2"></div>
        <Navbar />
        {children}
       </Providers>
      </body>
    </html>
  );
}
